name: xrdslam
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2023.11.17
  - certifi=2023.11.17
  - charset-normalizer=3.3.2
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - ffmpeg=4.3
  - filelock=3.13.1
  - freetype=2.12.1
  - gmp=6.3.0
  - gmpy2=2.1.2
  - gnutls=3.6.13
  - icu=73.2
  - idna=3.6
  - intel-openmp=2023.1.0
  - jinja2=3.1.3
  - jpeg=9e
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.8.1.2
  - libcurand=10.3.4.107
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.17
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - libhwloc=2.9.3
  - libiconv=1.17
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - libnpp=11.8.0.86
  - libnsl=2.0.1
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libsqlite=3.44.2
  - libstdcxx-ng=13.2.0
  - libtiff=4.5.0
  - libuuid=2.38.1
  - libwebp-base=1.3.2
  - libxcb=1.13
  - libxcrypt=4.4.36
  - libxml2=2.12.4
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.6
  - networkx=3.2.1
  - numpy=1.26.3
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openssl=3.2.0
  - pillow=9.4.0
  - pip=23.3.2
  - pthread-stubs=0.4
  - pysocks=1.7.1
  - python=3.10.13
  - python_abi=3.10
  - pytorch=2.1.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - readline=8.2
  - requests=2.31.0
  - setuptools=69.0.3
  - sympy=1.12
  - tbb=2021.11.0
  - tk=8.6.13
  - torchaudio=2.1.1
  - torchtriton=2.1.0
  - torchvision=0.16.1
  - typing_extensions=4.9.0
  - urllib3=2.1.0
  - wheel=0.42.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - addict==2.4.0
      - ansi2html==1.9.1
      - asttokens==2.4.1
      - attrs==23.2.0
      - blinker==1.7.0
      - click==8.1.7
      - comm==0.2.1
      - configargparse==1.7
      - contourpy==1.2.0
      - cycler==0.12.1
      - dash==2.14.2
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - decorator==5.1.1
      - docstring-parser==0.15
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - fastjsonschema==2.19.1
      - flask==3.0.0
      - fonttools==4.47.2
      - fsspec==2023.12.2
      - fvcore==0.1.5.post20221221
      - imageio==2.33.1
      - importlib-metadata==7.0.1
      - iopath==0.1.10
      - ipython==8.20.0
      - ipywidgets==8.1.1
      - itsdangerous==2.1.2
      - jedi==0.19.1
      - joblib==1.3.2
      - jsonschema==4.21.0
      - jsonschema-specifications==2023.12.1
      - jupyter-core==5.7.1
      - jupyterlab-widgets==3.0.9
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - lightning-utilities==0.10.0
      - lpips==0.1.4
      - markdown-it-py==3.0.0
      - mathutils==3.3.0
      - matplotlib==3.8.2
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - natsort==8.4.0
      - nbformat==5.5.0
      - nest-asyncio==1.5.9
      - open3d==0.16.0
      - opencv-python==4.9.0.80
      - packaging==23.2
      - pandas==2.1.4
      - parso==0.8.3
      - pexpect==4.9.0
      - platformdirs==4.1.0
      - plotly==5.18.0
      - portalocker==2.8.2
      - prompt-toolkit==3.0.43
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pygments==2.17.2
      - pyparsing==3.1.1
      - pyquaternion==0.9.9
      - python-dateutil==2.8.2
      - pytorch-msssim==1.0.0
      - pytz==2023.3.post1
      - referencing==0.32.1
      - retrying==1.3.4
      - rich==13.7.0
      - rpds-py==0.17.1
      - rtree==1.1.0
      - scikit-image==0.22.0
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - seaborn==0.13.1
      - shtab==1.6.5
      - six==1.16.0
      - stack-data==0.6.3
      - tabulate==0.9.0
      - tenacity==8.2.3
      - termcolor==2.4.0
      - threadpoolctl==3.2.0
      - tifffile==2023.12.9
      - torch-scatter==2.1.2
      - torchmetrics==1.3.0.post0
      - tqdm==4.66.1
      - traitlets==5.14.1
      - trimesh==3.21.5
      - tyro==0.6.4
      - tzdata==2023.4
      - wcwidth==0.2.13
      - werkzeug==3.0.1
      - widgetsnbextension==4.0.9
      - yacs==0.1.8
      - zipp==3.17.0
      - faiss-gpu==1.7.2
      - git+https://github.com/facebookresearch/pytorch3d.git
      - git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
      - git+https://github.com/JonathonLuiten/diff-gaussian-rasterization-w-depth.git@cb65e4b86bc3bd8ed42174b72a62e8d3a3a71110
