name: lint

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pre-commit hook
      run: |
        sudo apt-add-repository ppa:brightbox/ruby-ng -y
        sudo apt-get update
        sudo apt-get install -y ruby2.7
        pip install pre-commit
        pre-commit install
    - name: Linting
      run: pre-commit run --all-files
